package it.uniroma3.siw.progetto.models;

import java.util.ArrayList;
import java.util.List;

public final class Paesi {
	
	private List<String> paesi;
	
	public Paesi() {
		paesi = new ArrayList<String>();
		paesi.add("Afghanistan");
		paesi.add("Albania");
		paesi.add("Algeria");
		paesi.add("Andorra");
		paesi.add("Angola");
		paesi.add("Antartide");
		paesi.add("Arabia Saudita");
		paesi.add("Argentina");
		paesi.add("Armenia");
		paesi.add("Australia");
		paesi.add("Austria");
		paesi.add("Azerbaigian");
		paesi.add("Bahamas");
		paesi.add("Bahrein");
		paesi.add("Bangladesh");
		paesi.add("Barbados");
		paesi.add("Belgio");
		paesi.add("Bermuda");
		paesi.add("Bielorussia");
		paesi.add("Birmania");
		paesi.add("Bolivia");
		paesi.add("Bosnia-Erzegovina");
		paesi.add("Brasile");
		paesi.add("Bulgaria");
		paesi.add("Burkina Faso");
		paesi.add("Burundi");
		paesi.add("Cambogia");
		paesi.add("Camerun");
		paesi.add("Canada");
		paesi.add("Capo Verde");
		paesi.add("Ciad");
		paesi.add("Cile");
		paesi.add("Cina");
		paesi.add("Cipro");
		paesi.add("Cisgiordania");
		paesi.add("Città del Vaticano");
		paesi.add("Colombia");
		paesi.add("Corea del Nord");
		paesi.add("Corea del Sud");
		paesi.add("Costa d'Avorio");
		paesi.add("Costa Rica");
		paesi.add("Croazia");
		paesi.add("Cuba");
		paesi.add("Danimarca");
		paesi.add("Ecuador");
		paesi.add("Egitto");
		paesi.add("El Salvador");
		paesi.add("Emirati Arabi Uniti");
		paesi.add("Eritrea");
		paesi.add("Estonia");
		paesi.add("Etiopia");
		paesi.add("Fiji");
		paesi.add("Filippine");
		paesi.add("Finlandia");
		paesi.add("Francia");
		paesi.add("Germania");
		paesi.add("Ghana");
		paesi.add("Giamaica");
		paesi.add("Giappone");
		paesi.add("Giordania");
		paesi.add("Grecia");
		paesi.add("Groenlandia");
		paesi.add("Guadalupa");
		paesi.add("Guatemala");
		paesi.add("Guinea");
		paesi.add("Haiti");
		paesi.add("Honduras");
		paesi.add("Hong Kong");
		paesi.add("India");
		paesi.add("Indonesia");
		paesi.add("Iran");
		paesi.add("Iraq");
		paesi.add("Irlanda");
		paesi.add("Islanda");
		paesi.add("Israele");
		paesi.add("Italia");
		paesi.add("Kazakistan");
		paesi.add("Kenya");
		paesi.add("Kirghizistan");
		paesi.add("Kuwait");
		paesi.add("Laos");
		paesi.add("Lettonia");
		paesi.add("Libano");
		paesi.add("Liberia");
		paesi.add("Libia");
		paesi.add("Liechtenstein");
		paesi.add("Lituania");
		paesi.add("Lussemburgo");
		paesi.add("Macao");
		paesi.add("Macedonia");
		paesi.add("Madagascar");
		paesi.add("Maldive");
		paesi.add("Malesia");
		paesi.add("Mali");
		paesi.add("Malta");
		paesi.add("Marocco");
		paesi.add("Messico");
		paesi.add("Moldavia");
		paesi.add("Monaco");
		paesi.add("Mongolia");
		paesi.add("Montenegro");
		paesi.add("Mozambico");
		paesi.add("Namibia");
		paesi.add("Nepal");
		paesi.add("Nicaragua");
		paesi.add("Nigeria");
		paesi.add("Norvegia");
		paesi.add("Nuova Zelanda");
		paesi.add("Paesi Bassi");
		paesi.add("Pakistan");
		paesi.add("Panama");
		paesi.add("Papua Nuova Guinea");
		paesi.add("Paraguay");
		paesi.add("Perù");
		paesi.add("Polinesia francese");
		paesi.add("Polonia");
		paesi.add("Portogallo");
		paesi.add("Qatar");
		paesi.add("Regno Unito");
		paesi.add("Repubblica Ceca");
		paesi.add("Repubblica Democratica del Congo");
		paesi.add("Repubblica Dominicana");
		paesi.add("Romania");
		paesi.add("Ruanda");
		paesi.add("Russia");
		paesi.add("San Marino");
		paesi.add("Senegal");
		paesi.add("Serbia");
		paesi.add("Sierra Leone");
		paesi.add("Singapore");
		paesi.add("Siria");
		paesi.add("Slovacchia");
		paesi.add("Slovenia");
		paesi.add("Somalia");
		paesi.add("Spagna");
		paesi.add("Sri Lanka");
		paesi.add("Stati Uniti");
		paesi.add("Sud Sudan");
		paesi.add("Sudafrica");
		paesi.add("Sudan");
		paesi.add("Svezia");
		paesi.add("Svizzera");
		paesi.add("Tailandia");
		paesi.add("Taiwan");
		paesi.add("Tanzania");
		paesi.add("Tunisia");
		paesi.add("Turchia");
		paesi.add("Ucraina");
		paesi.add("Uganda");
		paesi.add("Ungheria");
		paesi.add("Uruguay");
		paesi.add("Uzbekistan");
		paesi.add("Venezuela");
		paesi.add("Vietnam");
		paesi.add("Yemen");
		paesi.add("Zambia");
		paesi.add("Zimbabwe");
	}

	public List<String> getPaesi() {
		return paesi;
	}
	
	

}
